#!/bin/bash
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- haproxy "$@"
fi

if [ "$1" = 'haproxy' ]; then
	shift # "haproxy"
	# if the user wants "haproxy", let's add a couple useful flags
	#   -W  -- "master-worker mode" (similar to the old "haproxy-systemd-wrapper"; allows for reload via "SIGUSR2")
	#   -db -- disables background mode
	set -- haproxy -W -db "$@"
fi


inotifywait --daemon -r /etc/haproxy /etc/letsencrypt/haproxy.pem -e modify -e move -e create -e delete -e delete_self | while read path action file;
do
    haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -x /var/run/haproxy.sock -sf $(cat /var/run/haproxy.pid) || true
done

js-yaml /data/config.yml | hbs -i /etc/haproxy/haproxy.cfg.hbs -s > /etc/haproxy/haproxy.cfg
