version: "3"
services:
  v2ray:
    image: v2ray/official
    restart: unless-stopped
    ports:
      - "53:53"
      - "53:53/udp"
      - "1088:1088"
      - "1089:1089"
    networks:
      - webnet
    volumes:
      - ./data/v2ray/vmess/:/etc/v2ray/
networks:
  webnet:
