version: "3"
services:
  centroid:
    build: ../images/v2ray
    image: centroid
    restart: always
    ports:
      - "53:53"
      - "53:53/udp"
      - "1088:1088"
      - "1089:1089"
      - "1090:1090"
    networks:
      - webnet
    volumes:
      - ../common/:/data
      - ./data/v2ray/vmess/:/etc/v2ray/
networks:
  webnet:
