version: "3.8"
services:
  certbot:
    image: certbot
    build: ../images/certbot
    restart: always
    volumes:
      - ../common:/data
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  haproxy:
    # replace username/repo:tag with your name and image details
    image: haproxy
    build: ../images/haproxy
    restart: always
    ports:
      - "443:443"
    networks:
      - webnet
    volumes:
      - ../common:/data
      - ./data/haproxy:/usr/local/etc/haproxy/
      - ./data/certbot/conf:/etc/letsencrypt
  vmess:
    build: ../images/v2ray
    image: vmess
    restart: always
    networks:
      - webnet
    volumes:
      - ../common/:/data
      - ./data/v2ray/vmess/:/etc/v2ray/
  shadowsocks:
    build: ../images/v2ray
    image: shadowsocks
    restart: always
    networks:
      - webnet
    volumes:
      - ../common/:/data
      - ./data/v2ray/shadowsocks/:/etc/v2ray/
  nginx:
    build: ../images/nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - webnet
      - hooked
    volumes:
      - ./data/nginx:/etc/nginx
      - ./data/certbot/www:/var/www/certbot
      - type: volume
        source: hooked
        target: /etc/nginx/conf.h
        bind:
          propagation: shared
networks:
  webnet:
    name: v2ray
  hooked:
    name: v2ray-hooked
volumes:
  haproxy:
  v2ray:
  hooked:
    name: v2ray-hooked
