#!/bin/bash
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- v2ray "$@"
fi

if [ "$1" = 'v2ray' ]; then
	shift 
fi



js-yaml /data/data.yml | hbs -i /etc/v2ray/config.json.hbs -s > /etc/v2ray/config.json   

exec "$@"
