#!/bin/sh
DOMAIN_ARGS=$(echo $DOMAINS|sed $'s/:/\\\n/g' | awk '{printf " -d " $1}')
echo "certbot certonly --webroot -w /var/www/certbot --email ${EMAIL} ${DOMAIN_ARGS} --rsa-key-size 4096 --agree-tos --force-renewal --non-interactive" | sh -x
find /etc/letsencrypt/live \( -name "fullchain.pem" -o  -name "privkey.pem" \) -exec cat {} \; > /etc/letsencrypt/haproxy.pem
