#!/bin/sh
trap exit TERM;
while :; do
    certbot renew && find /etc/letsencrypt/live \( -name 'fullchain.pem' -o  -name 'privkey.pem' \) -exec cat {} \; > /etc/letsencrypt/haproxy.pem;
    sleep 12h & wait $!;
done;
