protocols:
  - name: shadowsocks
    credentials:
      method: aes-256-gcm
      password: Pa$$w0rd
    server:
      port: 81
      address: s.opinion.works
    client:
  - name: vmess
    credentials:
      - id: d314c65c-f70f-4e1d-91fa-46821204a41a
        alterId: 64
      - id: 7a3f4b81-ec60-4ffe-8c09-d9d21cbfb50c
        alterId: 63
      - id: ef3452d0-e2ed-4d90-8d2c-7fce1505cf07
        alterId: 62
    server:
      port: 80
      address: v.opinion.works
