#!/bin/bash
while ! find /etc/letsencrypt/live  -maxdepth 1 -type d -not -path /etc/letsencrypt/live
do
    DOMAIN_ARGS=$(yq r /data/config.yml "letsencrypt.domains" |awk '{print $2}' | paste -sd, -)
    EMAIL=$(yq r /data/config.yml "letsencrypt.email")
    echo "certbot certonly --webroot -w /var/www/certbot --email ${EMAIL} -d ${DOMAIN_ARGS} --rsa-key-size 4096 --agree-tos --force-renewal --non-interactive" | sh -x
    sleep 60
done

find /etc/letsencrypt/live \( -name "fullchain.pem" -o  -name "privkey.pem" \) -exec cat {} \; > /etc/letsencrypt/haproxy.pem
    
trap exit TERM;
sleep 12h;

while :; do
    certbot renew && find /etc/letsencrypt/live \( -name 'fullchain.pem' -o  -name 'privkey.pem' \) -exec cat {} \; > /etc/letsencrypt/haproxy.pem;
    sleep 12h & wait $!;
done;
